### ISSUE TITLE
AttrDict does not provide simple constructor

### ISSUE THREAD

**Issue by rbu** [bcj/AttrDict#19]
This somewhat relates to #18, but I would like to raise this issue independently.

```
> dict(a=23) == dict(dict(a=23))
True

> AttrDict(a=23) == AttrDict(dict(a=23))
...
TypeError: __init__() got an unexpected keyword argument 'a'
```

The ```**kwargs``` based constructor of dict is incredibly helpful.

**Comment by bcj** [comment]
Fixed as of 2.0
