### ISSUE TITLE
AttrDict.get() does not return AttrDict but dict on nested AttrDicts

### ISSUE THREAD

**Issue by timgkeller** [bcj/AttrDict#25]
Hello everyone,

\>>> test = AttrDict({"a": {"b": "c"}})
\>>> type(test.a)
\<class 'attrdict.AttrDict'>
\>>> type(test.get("a"))
\<type 'dict'>

Is this behavior wanted or do you think as well that it is something worth changing?

As a workaround I am using: a = test.a if "a" in test else None

Best regards and thank you for this module,
Tim

**Comment by bcj** [comment]
Sorry for the slow response.

I view this as expected behavior. My stance has been attribute-style access results in an AttrDict, and key-style access results in a dict.

There is a way of replicating `get`'s functionality while returning an AttrDict:
```
>>> test = AttrDict({"a": {"b": "c"}})
>>> type(test.a)
<class 'attrdict.AttrDict'>
>>> type(test("a"))
<type 'attrdict.AttrDict'>
```
